### ISSUE TITLE
compatible with lower version browsers

### ISSUE THREAD

**Issue by huanz** [sindresorhus/p-try#7]
please compile source code or not use `const` and arrow function

**Comment by sindresorhus** [comment]
This module mainly targets Node.js and newer browsers, not older browsers. It's up to you to transpile it with Babel if you want to use it in older browsers.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
